version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: referral-mysql
    environment:
      MYSQL_DATABASE: referral_platform
      MYSQL_USER: referral_user
      MYSQL_PASSWORD: referral_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
